export const APP_SET_TRANSPLANTS_ALL = 'APP_SET_TRANSPLANTS_ALL';
export const APP_SET_TRANSPLANTS_0 = 'APP_SET_TRANSPLANTS_0';
export const APP_SET_TRANSPLANTS_1 = 'APP_SET_TRANSPLANTS_1';
export const APP_SET_TRANSPLANTS_2 = 'APP_SET_TRANSPLANTS_2';
export const APP_SET_TRANSPLANTS_3 = 'APP_SET_TRANSPLANTS_3';